<a href="https://colab.research.google.com/github/ShouryaBatra/fbla-data-analysis/blob/main/olympics_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

athletes = pd.read_csv("athlete_events.csv")
nocs = pd.read_csv("noc_regions.csv")

In [6]:
athletes.head()
athletes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [7]:
df = athletes.merge(nocs, on="NOC", how="left")

In [8]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,NaN

In [9]:
df["Medal_Won"] = df["Medal"].notna().astype(int)

In [10]:
df["Gold"] = (df["Medal"] == "Gold").astype(int)
df["Silver"] = (df["Medal"] == "Silver").astype(int)
df["Bronze"] = (df["Medal"] == "Bronze").astype(int)

In [11]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,...,City,Sport,Event,Medal,region,notes,Medal_Won,Gold,Silver,Bronze
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,...,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,...,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,...,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,...,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,1,1,0,0
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,...,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,NaN,0,0,0,0

In [12]:
df[["Age", "Height", "Weight"]].isna().mean()

Age       0.034944
Height    0.221938
Weight    0.231912
dtype: float64

In [13]:
df = df[df["Season"] == "Summer"]

In [14]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,...,City,Sport,Event,Medal,region,notes,Medal_Won,Gold,Silver,Bronze
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,...,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,...,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,...,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,...,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,1,1,0,0
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,...,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0,0

In [15]:
athlete_counts = (
    df.groupby(["region", "Sport"])["ID"]
    .nunique()
    .reset_index(name="Athletes_Sent")
)
athlete_counts.head()

        region      Sport  Athletes_Sent
0  Afghanistan  Athletics             14
1  Afghanistan     Boxing              5
2  Afghanistan   Football             11
3  Afghanistan     Hockey             33
4  Afghanistan       Judo              3

In [16]:
medal_counts = (
    df[df["Medal_Won"] == 1]
    .groupby(["region", "Sport"])["Medal_Won"]
    .sum()
    .reset_index(name="Medals_Won")
)
medal_counts.head()

        region      Sport  Medals_Won
0  Afghanistan  Taekwondo           2
1      Algeria  Athletics           9
2      Algeria     Boxing           6
3      Algeria       Judo           2
4    Argentina  Athletics           5

In [17]:
efficiency = athlete_counts.merge(
    medal_counts,
    on=["region", "Sport"],
    how="left"
).fillna(0)

efficiency["Medal_Efficiency"] = (
    efficiency["Medals_Won"] / efficiency["Athletes_Sent"]
)

efficiency.head()

        region      Sport  Athletes_Sent  Medals_Won  Medal_Efficiency
0  Afghanistan  Athletics             14         0.0               0.0
1  Afghanistan     Boxing              5         0.0               0.0
2  Afghanistan   Football             11         0.0               0.0
3  Afghanistan     Hockey             33         0.0               0.0
4  Afghanistan       Judo              3         0.0               0.0

In [18]:
df = df.rename(columns={"region": "Country"})
athlete_counts = athlete_counts.rename(columns={"region": "Country"})
medal_counts = medal_counts.rename(columns={"region": "Country"})
efficiency = efficiency.rename(columns={"region": "Country"})

In [19]:
sport_efficiency = (
    efficiency.groupby("Sport")
    .agg(
        Total_Athletes=("Athletes_Sent", "sum"),
        Total_Medals=("Medals_Won", "sum")
    )
)

sport_efficiency["Medal_Efficiency"] = (
    sport_efficiency["Total_Medals"] / sport_efficiency["Total_Athletes"]
)

sport_efficiency.sort_values("Medal_Efficiency", ascending=False).head(10)

               Total_Athletes  Total_Medals  Medal_Efficiency
Sport
Racquets                    7          10.0          1.428571
Rugby                     156         162.0          1.038462
Aeronautics                 1           1.0          1.000000
Alpinism                    4           4.0          1.000000
Cricket                    24          24.0          1.000000
Lacrosse                   60          60.0          1.000000
Basque Pelota               2           2.0          1.000000
Croquet                    10           8.0          0.800000
Polo                       87          67.0          0.770115
Roque                       4           3.0          0.750000

In [20]:
age_by_sport = (
    df.groupby(["Sport", "Medal_Won"])["Age"]
    .median()
    .unstack()
)
age_by_sport.head()

Medal_Won            0     1
Sport
Aeronautics        NaN  26.0
Alpinism           NaN  35.0
Archery           25.0  27.0
Art Competitions  45.0  41.0
Athletics         25.0  24.0

In [21]:
sport_participation = (
    df.groupby("Sport")["ID"]
    .nunique()
    .sort_values(ascending=False)
)

sport_participation.head(10)

Sport
Athletics     22071
Swimming       8765
Rowing         7687
Football       6161
Cycling        5819
Boxing         5262
Wrestling      4988
Shooting       4882
Sailing        4480
Gymnastics     4134
Name: ID, dtype: int64

In [22]:
countries_per_sport = (
    df.groupby("Sport")["Country"]
    .nunique()
    .sort_values(ascending=False)
)

countries_per_sport.head(10)

Sport
Athletics        203
Swimming         186
Judo             168
Boxing           161
Weightlifting    138
Cycling          134
Shooting         132
Wrestling        120
Sailing          111
Taekwondo        105
Name: Country, dtype: int64

In [23]:
sport_efficiency.sort_values("Medal_Efficiency", ascending=False).head(15)

                Total_Athletes  Total_Medals  Medal_Efficiency
Sport
Racquets                     7          10.0          1.428571
Rugby                      156         162.0          1.038462
Aeronautics                  1           1.0          1.000000
Alpinism                     4           4.0          1.000000
Cricket                     24          24.0          1.000000
Lacrosse                    60          60.0          1.000000
Basque Pelota                2           2.0          1.000000
Croquet                     10           8.0          0.800000
Polo                        87          67.0          0.770115
Roque                        4           3.0          0.750000
Tug-Of-War                 160         115.0          0.718750
Figure Skating              45          27.0          0.600000
Gymnastics                4148        2256.0          0.543877
Motorboating                14           7.0          0.500000
Softball                   367         179.0          0.487738

In [24]:
medals_by_country_sport = (
    df[df["Medal_Won"] == 1]
    .groupby(["Country", "Sport"])["Medal_Won"]
    .sum()
    .reset_index()
)

total_medals_by_country = (
    medals_by_country_sport
    .groupby("Country")["Medal_Won"]
    .sum()
    .reset_index(name="Total_Medals")
)

country_sport_share = medals_by_country_sport.merge(
    total_medals_by_country,
    on="Country"
)

country_sport_share["Share_of_Medals"] = (
    country_sport_share["Medal_Won"] /
    country_sport_share["Total_Medals"]
)
country_sport_share.head()

       Country      Sport  Medal_Won  Total_Medals  Share_of_Medals
0  Afghanistan  Taekwondo          2             2         1.000000
1      Algeria  Athletics          9            17         0.529412
2      Algeria     Boxing          6            17         0.352941
3      Algeria       Judo          2            17         0.117647
4    Argentina  Athletics          5           274         0.018248

In [25]:
medal_ages = (
    df[(df["Medal_Won"] == 1) & (df["Age"].notna())]
    [["Sport", "Age"]]
)

In [28]:
age_iqr_by_sport = (
    medal_ages
    .groupby("Sport")["Age"]
    .agg(
        Median_Age="median",
        Q1_Age=lambda x: x.quantile(0.25),
        Q3_Age=lambda x: x.quantile(0.75),
        Medal_Count="count"
    )
    .reset_index()
)

age_iqr_by_sport["IQR"] = (
    age_iqr_by_sport["Q3_Age"] - age_iqr_by_sport["Q1_Age"]
)
age_iqr_by_sport.head()

              Sport  Median_Age  Q1_Age  Q3_Age  Medal_Count    IQR
0       Aeronautics        26.0   26.00    26.0            1   0.00
1          Alpinism        35.0   25.75    44.5            4  18.75
2           Archery        27.0   22.00    38.0          319  16.00
3  Art Competitions        41.0   34.75    49.0          152  14.25
4         Athletics        24.0   22.00    27.0         3945   5.00

In [29]:
age_iqr_by_sport = age_iqr_by_sport[
    age_iqr_by_sport["Medal_Count"] >= 100
]

In [30]:
age_iqr_by_sport.sort_values("Median_Age").head(10)

                    Sport  Median_Age  Q1_Age  Q3_Age  Medal_Count   IQR
32    Rhythmic Gymnastics        18.0    17.0   20.25          132  3.25
40               Swimming        21.0    18.0   23.00         3027  5.00
15                 Diving        22.0    19.0   25.00          423  6.00
10                 Boxing        23.0    21.0   25.00          931  4.00
43              Taekwondo        23.0    21.0   26.00          144  5.00
41  Synchronized Swimming        23.0    22.0   26.00          215  4.00
19               Football        23.0    22.0   27.00         1531  5.00
21             Gymnastics        23.0    20.0   27.00         2187  7.00
14                Cycling        24.0    21.0   27.00         1235  6.00
4               Athletics        24.0    22.0   27.00         3945  5.00

In [31]:
age_iqr_by_sport.sort_values("Median_Age", ascending=False).head(10)

                Sport  Median_Age  Q1_Age  Q3_Age  Medal_Count    IQR
3    Art Competitions        41.0   34.75    49.0          152  14.25
16      Equestrianism        34.0   29.00    41.0          955  12.00
38           Shooting        32.0   27.00    39.0         1167  12.00
37            Sailing        30.0   26.00    36.0         1175  10.00
17            Fencing        28.0   24.00    32.0         1720   8.00
2             Archery        27.0   22.00    38.0          319  16.00
28  Modern Pentathlon        27.0   25.00    29.0          186   4.00
11           Canoeing        26.0   23.00    29.0         1165   6.00
6            Baseball        26.0   23.00    29.0          336   6.00
39           Softball        26.0   24.00    29.0          179   5.00